# rules: https://dart-lang.github.io/linter/lints/options/options.html
# customize: https://dart.dev/guides/language/analysis-options#disabling-individual-rules

analyzer:
  strong-mode:
    implicit-casts: false

  errors:
    invalid_assignment: error
    dead_code: error

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    avoid_positional_boolean_parameters: false
    always_require_non_null_named_parameters: true
    avoid_classes_with_only_static_members: false
    avoid_empty_else: true
    avoid_final_parameters: true
    avoid_implementing_value_types: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_setters_without_getters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    camel_case_extensions: true
    camel_case_types: true
    comment_references: true
    flutter_style_todos: true
    use_build_context_synchronously: false
    curly_braces_in_flow_control_structures: true
    unnecessary_brace_in_string_interps: true
    no_leading_underscores_for_local_identifiers: false
    use_colored_box: false
    use_decorated_box: false
